# State Farm Data Scientist  Preemployement Assessment: A Classification problem

**Step 1: I will first load both test data and Clean up the data as we did on the Training set and prepare the file for deployement.**

In [205]:
# Before any thing else lets load some basic python libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [206]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings("ignore")

In [207]:
#now read the training data 
tst_raw=pd.read_csv('exercise_40_test.csv')
tst_raw.head(10)
#print(tst_raw.shape)

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x80,x81,x82,x83,x84,x85,x86,x87,x88,x89,x90,x91,x92,x93,x94,x95,x96,x97,x98,x99,x100
0,4.747627,20.509439,Wednesday,2.299105,-1.815777,-0.752166,0.0098%,-3.240309,0.587948,-0.260721,101.113628,-0.812035,3.251085,-0.004432,-0.917763,102.193597,7.097387,75.256714,$120.216189955777,8.269754,4.794438,56.134458,-0.083641,NaN,5.740955,-3.152540,924.013304,17.697125,1.402273,NaN,no,1.461654,Florida,57.930285,4.727300,66.416594,28.450466,33.499310,5-10 miles,16.776061,99971.844703,0.492812,-0.963616,NaN,NaN,1.266416,53.020326,61.840284,NaN,1825.413159,2.517924,NaN,70.880778,NaN,1.923125,0.239009,NaN,300.629990,0,May,5.461123,5.149473,1.179229,59.346822,progressive,2.219502,17.667792,5.557066,-2.030901,0.636111,-0.000234,62.363381,4.613878,2.415655,3.632041,-0.382482,mercedes,55.938387,1.0,8.325299,-1.274085,-5.663245,2.402660,-0.061040,NaN,64.002500,0.548974,3.420875,11.553023,5.904644,NaN,12.542333,no,3.107683,0.533904,12.438759,7.298306,0,NaN,93.567120
1,1.148654,19.301465,Fri,1.862200,-0.773707,-1.461276,0.0076%,0.443209,0.522113,-1.090886,104.791999,8.805876,1.651993,NaN,-1.396065,99.356609,7.117930,79.061540,$-267.562586413086,5.668347,12.377178,NaN,0.321981,female,2.058123,-0.442525,1107.628399,15.747234,2.027073,NaN,yes,0.608259,North Carolina,55.646392,0.789132,68.881807,32.242558,-1.034680,5-10 miles,11.959804,99910.554923,0.547935,1.001799,1.315020,3.229084,5.873890,49.116516,61.279131,9.360134,1818.390072,2.269700,0.336755,69.832156,2.666487,1.224195,-1.214940,NaN,300.629990,0,July,6.520113,2.101449,-0.871509,NaN,allstate,1.289800,14.402071,7.302161,-1.553879,1.352019,-0.000234,54.104054,9.010198,0.537178,1.489493,-1.106853,ford,44.322947,1.0,6.088895,1.878944,-8.237793,3.636347,3.726452,105.488589,53.387201,-0.751229,0.295234,6.212811,4.876645,-0.848567,7.213829,yes,4.276078,NaN,10.386987,12.527094,1,yes,98.607486
2,4.986860,18.769675,Saturday,1.040845,-1.548690,2.632948,-5e-04%,-1.167885,5.739275,0.222975,102.109546,7.831517,3.055358,2.036434,1.057296,NaN,10.943217,87.567827,$-311.292903116571,3.219583,31.135956,50.048638,1.174485,male,1.609278,-0.303259,1009.911508,12.008190,0.618778,NaN,no,0.680923,NaN,53.178113,0.869321,70.249633,35.207243,48.980294,5-10 miles,14.564732,100729.380783,0.096947,-0.490053,NaN,1.333292,0.750075,48.258898,63.737244,11.564194,1815.680559,1.704048,NaN,67.090400,1.547230,NaN,1.428580,NaN,300.629990,0,January,12.190433,1.793349,-0.114922,48.121885,progressive,-1.755707,14.402071,9.903803,1.720469,0.765756,-0.000234,51.522621,11.700359,-1.867170,0.383319,-1.078648,NaN,48.854080,1.0,8.711055,-0.073306,-8.739095,NaN,2.138771,NaN,49.687134,2.641871,1.718243,NaN,4.455432,1.143388,10.483928,no,2.090868,-1.780474,11.328177,11.628247,0,yes,94.578246
3,3.709183,18.374375,Tuesday,-0.169882,-2.396549,-0.784673,-0.016%,-2.662226,1.548050,0.210141,82.653354,0.436885,1.578106,NaN,-1.287913,102.410965,6.588790,71.825782,$2229.14940030076,7.459929,1.822459,88.144007,0.909556,female,8.864059,0.641209,841.889126,20.904196,0.725017,NaN,no,0.622849,Mississippi,50.311869,0.453211,65.253390,34.432292,52.756665,5-10 miles,18.503815,101476.778846,0.888038,-0.007376,-1.126059,1.129508,-0.455920,44.525657,60.008453,12.852088,2251.680231,2.915405,5.895661,75.219207,NaN,NaN,-0.415800,NaN,300.629990,0,July,6.865209,5.083537,1.685063,46.761738,geico,-0.807993,14.402071,16.576216,0.033036,0.284538,-0.000234,54.625974,13.160347,-0.329204,2.171326,-0.109125,subaru,NaN,1.0,11.742605,-0.253294,-6.641284,4.755348,2.138771,NaN,NaN,1.811825,0.461637,18.198978,3.947223,0.693646,3.862867,no,2.643847,1.662240,10.064961,10.550014,1,NaN,100.346261
4,3.801616,20.205541,Monday,2.092652,-0.732784,-0.703101,0.0186%,0.056422,2.878167,-0.457618,75.036421,8.034303,1.631426,0.643738,0.349166,101.513490,5.777599,74.602441,$-469.049529991235,8.245194,0.904920,51.705319,-0.544762,female,2.408958,1.841905,885.172420,14.401750,4.059599,NaN,yes,1.073262,Georgia,39.646787,-0.686812,71.673393,37.257458,64.572325,5-10 miles,11.477353,99444.069807,0.597749,0.432984,NaN,2.973636,2.684343,46.377723,55.276157,15.245726,3377.213091,0.461064,9.296694,64.547880,2.196671,NaN,3.294733,NaN,300.629990,0,January,NaN,4.758357,-1.053362,49.328246,progressive,-0.943724,15.155869,24.834647,3.127852,1.427115,-0.000234,55.277258,14.443014,-1.075761,6.086487,-1.002809,ford,51.429529,0.0,11.602066,0.091523,-4.620275,2.060447,2.138771,NaN,49.747279,0.320393,0.930729,10.014853,1.637334,-0.834763,3.632039,yes,4.074434,NaN,9.255766,12.716137,1,yes,102.578918
5,1.449185,17.237848,Sun,0.998924,0.882350,-1.700730,0.0076%,-0.371594,1.269817,-1.433127,78.434085,3.124643,4.438999,NaN,-0.761186,102.214681,10.767388,77.358212,$1052.65320492622,4.483987,-0.962477,109.832593,-0.151157,female,4.441319,-0.596301,933.989898,15.966680,-0.734704,NaN,no,0.279159,Texas,61.483661,0.977712,67.624065,31.562690,55.465508,5-10 miles,19.699351,102129.701029,0.282302,1.718000,NaN,0.449438,1.018255,47.951034,63.604471,10.363016,1782.630074,2.158373,NaN,74.491964,NaN,2.279133,2.173747,NaN,185.757222,0,August,4.890171,4.177618,NaN,45.958659,allstate,0.205761,14.402071,14.639296,1.531711,0.476055,-0.000234,41.496501,10.216519,-1.408112,3.222602,NaN,chevrolet,52.896976,NaN,8.370684,1.397563,-7.737628,NaN,2.205569,104.383897,49.228114,1.765910,-0.361749,14.582317,4.913132,0.636832,2.990617,no,3.476341,NaN,10.226547,8.795927,0,yes,107.472726
6,0.979035,18.056038,Monday,0.105417,-1.782850,-1.390759,-0.0045%,-1.886515,2.905928,0.222237,87.040247,6.739816,2.839826,0.227705,-3.909978,100.183345,6.302176,81.401764,$-1248.56374994913,7.149937,2.683275,52.907015,0.173755,female,4.338434,-2.429951,960.386928,18.664972,-2.002736,NaN,no,0.640112,Texas,52.127077,1.162487,66.486798,38.238661,64.390768,5-10 miles,15.454190,101265.812744,NaN,2.393106,NaN,1.296644,-4.343251,44.602216,58.378596,14.554986,2705.205769,1.746380,NaN,74.153908,1.602342,0.640135,1.373997,NaN,300.629990,0,October,7.651008,0.088124,0.551207,39.652918,allstate,-4.253201,14.402071,25.385012,1.232327,0.454590,-0.000234,54.643485,8.001475,-2.605064,-0.010886,-2.379740,toyota,NaN,1.0,NaN,-0.739539,-6.723650,1.985845,7.959044,109.002251,44.582381,1.623425,-0.771061,9.040024,3.239272,0.622201,4.563410,no,4.311061,-1.757497,10.894402,11.669336,1,yes,97.736258
7,0.910023,17.057286,Mon,-0.903745,0.118699,-2.110974,-0.0079%,-0.613028,2.109169,1.140936,93.985642,1.006534,2.645002,0.938672,-1.301097,100.798786,5.676887,86.843134,$2192.44913918191,7.323247,10.156596,56.375428,-1.341493,male,4.136920,1.023571,1040.635068,12.349514,1.057818,NaN,no,-1.658936,West Virginia,53.392675,2.496354,69.025509,30.663928,0.005587,5-10 miles,18.453507,NaN,1.758723,0.665080,NaN,0.247599,2.025626,52.891423,53.032210,NaN,2234.287724,0.528161,NaN,72.271931,-0.073297,NaN,2.350433,NaN,300.629990,0,July,7.561739,2.862059,-1.252908,50.945053,allstate,-1.176805,13.854003,8.487633,1.602317,0.611340,-0.000234,51.003914,1.003110,-0.496488,1.231024,-3.266370,mercedes,53.650146,0.0,NaN,-1.228724,-8.662640,1.916580,10.803986,NaN,41.249394,-2.465411,0.653846,7.151094,4.587466,-3.446000,5.910630,no,4.615327,NaN,12.956667,9.710828,0,yes,103.143976
8,3.616287,17.740881,Thur,2.193121,4.222402,0.206030,-0.0201%,-0.397257,3.058279,-0.859673,120.832847,8.501188,2.386375,0.841161,2.918181,99.884976,3.951736,71.032462,$-744.50837755944,8.676654,10.553713,NaN,-0.557564,male,6.702953,-0.273125,1083.261779,11.395577,-0.342533,NaN,yes,2.608860,NaN,49.759026,2.447658,71.340434,29.164827,-1.773468,5-10 miles,13.343070,99405.481487,2.169503,-0.405920,NaN,-0.342653,0.543338,55.559868,58.999216,14.589907,1497.545917,3.126574,8.988697,65.473400,0.876886,3.393729,-0.953616,NaN,300.629990,0,December,9.117867,2.866405,2.400555,54.452831,progressive,0.979573,14.402071,19.348991,-0.550358,0.979911,-0.000234,50.057352,0.051196,0.415577,1.394603,-1.783284,subaru,42.741471,1.0,10.096028,0.892515,-9.176469,0.945468,2.138771,NaN,49.301555,-0.609911,2.268028,8.720701,4.471586,0.327317,4.247582,no,6.103622,0.449423,NaN,10.757233,0,yes,99.305236
9,2.539012,21.078729,Saturday,-0.868620,-0.193794,1.244369,-0.0222%,-0.334661,1.478947,0.637950,88.678380,-1.291054,2.964086,0.268776,-1.237706,NaN,7.867055,89.714961,$621.500064669709,5.846521,2.267503,96.053643,0.854394,male,9.404582,NaN,1000.124134,17.191532,-0.144120,NaN,yes,-2.338378,Florida,54.258922,1.354666,74.538751,30.880550,0.042106,5-10 miles,10.890634,99606.913905,-0.034069,1.521666,NaN,0.638664,-1.173450,40.845531,59.605631,7.593193,3714.830314,-0.068952,15.952439,66.383331,0.226369,3.661672,-0.154963,NaN,300.629990,1,July,14.765062,4.529053,-0.278867,40.625710,progressive,0.754390,14.402071,24.524638,-0.681237,0.870819,-0.000234,49.314144,7.744969,NaN,-0.361825,-0.351459,subaru,51.323289,1.0,11.700299,-0.009492,-7.983513,5.156862,2.138771,NaN,NaN,1.782405,0.009158,NaN,2.784435,-3.202012,2.336352,no,5.288189,NaN,10.258891,8.016081,0,NaN,99.593899

In [11]:
#lets define Categorical data
tst_raw_category=tst_raw.loc[:,tst_raw.dtypes==np.object]
#tst_raw_category.shape
tst_raw_category.head()

,x3,x7,x19,x24,x31,x33,x39,x60,x65,x77,x93,x99
0,Wednesday,0.0098%,$120.216189955777,NaN,no,Florida,5-10 miles,May,progressive,mercedes,no,NaN
1,Fri,0.0076%,$-267.562586413086,female,yes,North Carolina,5-10 miles,July,allstate,ford,yes,yes
2,Saturday,-5e-04%,$-311.292903116571,male,no,NaN,5-10 miles,January,progressive,NaN,no,yes
3,Tuesday,-0.016%,$2229.14940030076,female,no,Mississippi,5-10 miles,July,geico,subaru,no,NaN
4,Monday,0.0186%,$-469.049529991235,female,yes,Georgia,5-10 miles,January,progressive,ford,yes,yes

In [12]:
#summarize categorical variables
tst_raw_category.describe(include='all')

,x3,x7,x19,x24,x31,x33,x39,x60,x65,x77,x93,x99
count,10000,10000,10000,9031,10000,8230,10000,10000,10000,7682,10000,6700
unique,14,570,10000,2,2,51,1,12,5,7,2,1
top,Wednesday,8e-04%,$430.127440517153,female,no,California,5-10 miles,August,progressive,ford,no,yes
freq,1224,56,1,4532,8500,841,10000,2055,2703,2325,8848,6700

In [13]:
#based on this observation Column x39 and x99 are qunique with only one kind of values. So lets drop them
nunique = tst_raw_category.nunique()
cols_to_drop = nunique[nunique == 1].index
tst_raw_category = tst_raw_category.drop(cols_to_drop, axis=1)
tst_raw_category.describe(include='all')

,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
count,10000,10000,10000,9031,10000,8230,10000,10000,7682,10000
unique,14,570,10000,2,2,51,12,5,7,2
top,Wednesday,8e-04%,$430.127440517153,female,no,California,August,progressive,ford,no
freq,1224,56,1,4532,8500,841,2055,2703,2325,8848

In [14]:
#lets find the null values in these categorical data and impute them with mode(max frequency)methos
for col in tst_raw_category:
    max_freq = tst_raw_category[col].value_counts().index[0]
    tst_raw_category[col][pd.isna(tst_raw_category[col])] = max_freq

In [15]:
tst_raw_category.describe(include='all')

,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,14,570,10000,2,2,51,12,5,7,2
top,Wednesday,8e-04%,$430.127440517153,female,no,California,August,progressive,ford,no
freq,1224,56,1,5501,8500,2611,2055,2703,4643,8848

In [16]:
#now lets remove % sign from column x7 and x19
tst_raw_category['x7'] = tst_raw_category['x7'].replace('\%','',regex=True).astype(float)
tst_raw_category['x19'] = tst_raw_category['x19'].replace('\$','',regex=True).astype(float)
tst_raw_category.head()

,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
0,Wednesday,0.0098,120.216190,female,no,Florida,May,progressive,mercedes,no
1,Fri,0.0076,-267.562586,female,yes,North Carolina,July,allstate,ford,yes
2,Saturday,-0.0005,-311.292903,male,no,California,January,progressive,ford,no
3,Tuesday,-0.0160,2229.149400,female,no,Mississippi,July,geico,subaru,no
4,Monday,0.0186,-469.049530,female,yes,Georgia,January,progressive,ford,yes

In [17]:
#features X31 and X93 are binary class with Yes and no nominal values.Lets convert them into numerical values of 0 and 1
tst_raw_category['x31']=tst_raw_category['x31'].replace(['no','yes'],[0,1])
tst_raw_category['x93']=tst_raw_category['x93'].replace(['no','yes'],[0,1])
tst_raw_category.head()

,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
0,Wednesday,0.0098,120.216190,female,0,Florida,May,progressive,mercedes,0
1,Fri,0.0076,-267.562586,female,1,North Carolina,July,allstate,ford,1
2,Saturday,-0.0005,-311.292903,male,0,California,January,progressive,ford,0
3,Tuesday,-0.0160,2229.149400,female,0,Mississippi,July,geico,subaru,0
4,Monday,0.0186,-469.049530,female,1,Georgia,January,progressive,ford,1

In [18]:
# Now lets work with days and lets make them uniform Ordinal 
tst_raw_category["x3"].replace({"Sat": "Saturday", "Sun": "Sunday", "Mon": "Monday", "Tue": "Tuesday",
                  "Wed": "Wednesday", "Thur": "Thursday", "Fri": "Friday"}, inplace=True)

In [19]:
#Another nomial category is gender
tst_raw_category['x24']=tst_raw_category['x24'].replace(['female','male'],[0,1])
tst_raw_category.head()

,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
0,Wednesday,0.0098,120.216190,0,0,Florida,May,progressive,mercedes,0
1,Friday,0.0076,-267.562586,0,1,North Carolina,July,allstate,ford,1
2,Saturday,-0.0005,-311.292903,1,0,California,January,progressive,ford,0
3,Tuesday,-0.0160,2229.149400,0,0,Mississippi,July,geico,subaru,0
4,Monday,0.0186,-469.049530,0,1,Georgia,January,progressive,ford,1

In [20]:
#Now I will convert them with dictionary frequency,save to a mapping function and map it back to dictionary 
#Tried label encoder it did not worked properly. 
freq=tst_raw_category.x3.value_counts().to_dict()
tst_raw_category.x3=tst_raw_category.x3.map(freq)

In [21]:
# For States X33
freq1=tst_raw_category.x33.value_counts().to_dict()
tst_raw_category.x33=tst_raw_category.x33.map(freq1)

In [22]:
##for months x60
freq2=tst_raw_category.x60.value_counts().to_dict()
tst_raw_category.x60=tst_raw_category.x60.map(freq2)

In [23]:
#for months x65
freq3=tst_raw_category.x65.value_counts().to_dict()
tst_raw_category.x65=tst_raw_category.x65.map(freq3)

In [24]:
#for months x77
freq4=tst_raw_category.x77.value_counts().to_dict()
tst_raw_category.x77=tst_raw_category.x77.map(freq4)

In [25]:
tst_raw_category.head()

     x3      x7          x19  x24  x31   x33   x60   x65   x77  x93
0  1748  0.0098   120.216190    0    0   475   211  2703  1081    0
1  1471  0.0076  -267.562586    0    1   238  2050  2686  4643    1
2  1271 -0.0005  -311.292903    1    0  2611  1935  2703  4643    0
3  1698 -0.0160  2229.149400    0    0    85  2050  1332  1209    0
4  1527  0.0186  -469.049530    0    1   236  1935  2703  4643    1

In [27]:
#lets separate the data with numeric values only
tst_raw_num = tst_raw.loc[:,tst_raw.dtypes == np.float64]
tst_raw_num.head()

,x1,x2,x4,x5,x6,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x20,x21,x22,x23,x25,x26,x27,x28,x29,x30,x32,x34,x35,x36,x37,x38,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x61,x62,x63,x64,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x78,x79,x80,x81,x82,x83,x84,x85,x86,x87,x88,x89,x90,x91,x92,x94,x95,x96,x97,x100
0,4.747627,20.509439,2.299105,-1.815777,-0.752166,-3.240309,0.587948,-0.260721,101.113628,-0.812035,3.251085,-0.004432,-0.917763,102.193597,7.097387,75.256714,8.269754,4.794438,56.134458,-0.083641,5.740955,-3.152540,924.013304,17.697125,1.402273,NaN,1.461654,57.930285,4.727300,66.416594,28.450466,33.499310,16.776061,99971.844703,0.492812,-0.963616,NaN,NaN,1.266416,53.020326,61.840284,NaN,1825.413159,2.517924,NaN,70.880778,NaN,1.923125,0.239009,NaN,300.62999,5.461123,5.149473,1.179229,59.346822,2.219502,17.667792,5.557066,-2.030901,0.636111,-0.000234,62.363381,4.613878,2.415655,3.632041,-0.382482,55.938387,1.0,8.325299,-1.274085,-5.663245,2.402660,-0.061040,NaN,64.002500,0.548974,3.420875,11.553023,5.904644,NaN,12.542333,3.107683,0.533904,12.438759,7.298306,93.567120
1,1.148654,19.301465,1.862200,-0.773707,-1.461276,0.443209,0.522113,-1.090886,104.791999,8.805876,1.651993,NaN,-1.396065,99.356609,7.117930,79.061540,5.668347,12.377178,NaN,0.321981,2.058123,-0.442525,1107.628399,15.747234,2.027073,NaN,0.608259,55.646392,0.789132,68.881807,32.242558,-1.034680,11.959804,99910.554923,0.547935,1.001799,1.315020,3.229084,5.873890,49.116516,61.279131,9.360134,1818.390072,2.269700,0.336755,69.832156,2.666487,1.224195,-1.214940,NaN,300.62999,6.520113,2.101449,-0.871509,NaN,1.289800,14.402071,7.302161,-1.553879,1.352019,-0.000234,54.104054,9.010198,0.537178,1.489493,-1.106853,44.322947,1.0,6.088895,1.878944,-8.237793,3.636347,3.726452,105.488589,53.387201,-0.751229,0.295234,6.212811,4.876645,-0.848567,7.213829,4.276078,NaN,10.386987,12.527094,98.607486
2,4.986860,18.769675,1.040845,-1.548690,2.632948,-1.167885,5.739275,0.222975,102.109546,7.831517,3.055358,2.036434,1.057296,NaN,10.943217,87.567827,3.219583,31.135956,50.048638,1.174485,1.609278,-0.303259,1009.911508,12.008190,0.618778,NaN,0.680923,53.178113,0.869321,70.249633,35.207243,48.980294,14.564732,100729.380783,0.096947,-0.490053,NaN,1.333292,0.750075,48.258898,63.737244,11.564194,1815.680559,1.704048,NaN,67.090400,1.547230,NaN,1.428580,NaN,300.62999,12.190433,1.793349,-0.114922,48.121885,-1.755707,14.402071,9.903803,1.720469,0.765756,-0.000234,51.522621,11.700359,-1.867170,0.383319,-1.078648,48.854080,1.0,8.711055,-0.073306,-8.739095,NaN,2.138771,NaN,49.687134,2.641871,1.718243,NaN,4.455432,1.143388,10.483928,2.090868,-1.780474,11.328177,11.628247,94.578246
3,3.709183,18.374375,-0.169882,-2.396549,-0.784673,-2.662226,1.548050,0.210141,82.653354,0.436885,1.578106,NaN,-1.287913,102.410965,6.588790,71.825782,7.459929,1.822459,88.144007,0.909556,8.864059,0.641209,841.889126,20.904196,0.725017,NaN,0.622849,50.311869,0.453211,65.253390,34.432292,52.756665,18.503815,101476.778846,0.888038,-0.007376,-1.126059,1.129508,-0.455920,44.525657,60.008453,12.852088,2251.680231,2.915405,5.895661,75.219207,NaN,NaN,-0.415800,NaN,300.62999,6.865209,5.083537,1.685063,46.761738,-0.807993,14.402071,16.576216,0.033036,0.284538,-0.000234,54.625974,13.160347,-0.329204,2.171326,-0.109125,NaN,1.0,11.742605,-0.253294,-6.641284,4.755348,2.138771,NaN,NaN,1.811825,0.461637,18.198978,3.947223,0.693646,3.862867,2.643847,1.662240,10.064961,10.550014,100.346261
4,3.801616,20.205541,2.092652,-0.732784,-0.703101,0.056422,2.878167,-0.457618,75.036421,8.034303,1.631426,0.643738,0.349166,101.513490,5.777599,74.602441,8.245194,0.904920,51.705319,-0.544762,2.408958,1.841905,885.172420,14.401750,4.059599,NaN,1.073262,39.646787,-0.686812,71.673393,37.257458,64.572325,11.477353,99444.069807,0.597749,0.432984,NaN,2.973636,2.684343,46.377723,55.276157,15.245726,3377.213091,0.461064,9.296694,64.547880,2.196671,NaN,3.294733,NaN,300.62999,NaN,4.758357,-1.053362,49.328246,-0.943724,15.155869,24.834647,3.127852,1.427115,-0.000234,55.277258,14.443014,-1.075761,6.086487,-1.002809,51.429529,0.0,11.602066,0.091523,-4.620275,2.060447,2.138771,NaN,49.747279,0.320393,0.930729,10.014853,1.637334,-0.834763,3.632039,4.074434,NaN,9.255766,12.716137,102.578918

In [28]:
# Now lets create a new dataset with all numerical values
tst_clean=pd.concat([tst_raw_num,tst_raw_category], axis=1)

In [29]:
tst_clean.shape

(10000, 96)

In [30]:
#summarize categorical variables
tst_clean.describe(include='all')

,x1,x2,x4,x5,x6,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x20,x21,x22,x23,x25,x26,x27,x28,x29,x30,x32,x34,x35,x36,x37,x38,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x61,x62,x63,x64,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x78,x79,x80,x81,x82,x83,x84,x85,x86,x87,x88,x89,x90,x91,x92,x94,x95,x96,x97,x100,x3,x7,x19,x24,x31,x33,x60,x65,x77,x93
count,10000.000000,10000.000000,10000.000000,9398.000000,10000.000000,10000.000000,10000.000000,10000.000000,8671.000000,10000.000000,10000.000000,7572.000000,10000.000000,7247.000000,10000.000000,10000.000000,10000.000000,10000.000000,9387.000000,10000.000000,10000.000000,9383.000000,10000.000000,10000.000000,10000.000000,1915.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9435.000000,10000.000000,7596.000000,7582.000000,10000.000000,1434.000000,7937.000000,10000.000000,10000.000000,10000.000000,6746.000000,10000.000000,10000.000000,5920.000000,10000.000000,6794.000000,5576.000000,10000.000000,1923.000000,10000.000000,8234.000000,10000.000000,9413.000000,8738.000000,10000.000000,9380.000000,9400.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,6837.000000,8734.000000,8644.000000,7134.000000,9390.000000,8685.000000,10000.000000,10000.000000,9428.000000,10000.000000,7581.000000,9398.000000,10000.000000,9409.000000,7325.000000,10000.000000,8690.000000,9374.000000,9385.000000,6828.000000,8372.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2.944648,20.003002,0.004528,0.001215,0.001926,-0.003416,2.710221,0.506369,99.915979,3.019374,3.926723,0.784069,0.012419,100.727360,8.027597,80.026084,4.987877,11.117466,72.091235,0.189215,5.011489,-0.011677,999.005034,14.992886,0.978150,0.006684,0.550535,53.078686,1.387669,70.000737,30.988151,35.676454,15.043602,99982.619081,0.645443,0.513008,1.104018,0.565286,0.036462,50.046458,60.026938,10.277466,2094.418322,1.471573,4.733425,70.022077,0.020602,3.025879,0.487472,32.461509,300.674717,9.995180,3.843418,-0.004833,50.025191,-0.006610,14.401629,14.788857,0.008452,0.730233,0.006077,49.980794,6.935070,-0.005739,1.441040,-1.010219,50.033544,0.898509,10.040383,-0.008035,-6.126672,3.817244,2.148462,99.986491,50.035111,0.016275,0.453659,10.847434,3.007583,-0.003896,4.011856,3.949177,0.036814,10.564081,10.000062,99.942280,1466.075200,0.000008,-0.554811,0.449900,0.150000,858.923000,1676.011800,2174.201400,2706.353800,0.115200
std,2.018091,1.600368,1.449873,1.290027,1.363301,1.442214,1.985433,1.028552,13.254583,3.586150,2.706451,0.746441,1.482391,1.060159,2.283019,6.547863,3.547695,15.825830,27.229397,1.039170,2.437551,1.569508,104.846352,3.676316,1.401266,1.587620,1.874100,5.845842,1.605198,4.311982,3.403902,26.272060,3.237721,1363.732898,1.164881,1.025785,1.641046,1.219064,1.778882,4.402070,5.436317,2.727696,945.719816,1.610216,7.309549,4.961228,1.364694,1.848236,1.453488,8.419344,34.690659,3.440018,2.249602,1.509589,4.968724,1.481606,1.147804,6.311567,1.329897,0.363357,0.407164,6.499956,5.600800,1.445674,2.485056,1.219318,4.127081,0.301994,2.562332,1.550861,2.270473,2.532796,0.785153,10.642192,4.827958,1.196265,1.101479,3.840455,1.156709,1.479756,3.010645,1.467001,1.833016,1.460146,2.002298,5.302475,228.875664,0.009927,1006.365662,0.497509,0.357089,1050.680132,700.728971,581.595008,1813.816786,0.319279
min,-2.639067,13.790389,-4.768309,-4.662646,-5.720785,-5.627568,-3.160208,-3.452189,51.489501,-5.039053,-2.918862,-0.338883,-6.013757,99.131027,-0.264370,66.471523,-8.721968,-3.094312,2.816051,-3.504739,-3.035988,-5.798616,615.307402,1.870244,-3.170093,-4.574698,-4.073306,28.166134,-3.005756,54.232409,17.945555,-3.562433,9.999943,95193.915675,-1.187253,-3.202323,-3.319158,-1.318430,-6.227914,32.468040,37.728221,0.556815,-1673.925468,-3.006937,-21.418238,52.402252,-5.162871,0.249087,-4.680512,14.630926,101.376280,1.827238,-2.172217,-9.059326,32.340442,-6.483385,4.389352,0.650828,-4.133603,0.015258,-3.933177,25.785545,-2.871946,-4.379516,-3.564698,-6.426074,33.519567,0.000000,2.927019,-5.527865,-11.420765,-2.574451,-1.900415,58.671658,33.500796,-4.081535,-3.769385,6.106138,-1.652499,-5.563109,-3.889151,-0.970920,-6.512179,8.212286,2.444658,79.100558,1128.000000,-0.036100,-4497.412230,0.000000,0.000000,38.000000,182.000000,1332.000000,282.000000,0.000000
25%,1.522883,18.926348,-1.025638,-0.878598,-0.931917,-0.978422,1.328622,-0.196679,90.981197,-0.203236,1.991730,0.191783,-0.988190,99.885403,6.457095,74.074136,2.552522,1.359686,52.540203,-0.514637,3.299264,-1.042946,929.692219,12.498954,0.001233,-1.144359,-0.475393,49.058566,0.353986,67.095460,28.717372,16.850630,12.074160,99070.879988,-0.305527,-0.174594,0.033156,-0.401007,-1.156013,47.099402,56.389100,8.450101,1465.912201,0.354687,-0.240869,66.612698,-0.903126,1.540516,-0.511280,25.799589,300.629990,7.012192,2.254463,-0.964745,46.614430,-0.986255,14.402071,10.188464,-0.903609,0.453536,-0.000234,45.610562,2.955614,-1.020489,0.146120,-1.796734,47.192824,1.000000,8.126514,-1.049609,-7.797208,2.006995,2.138771,92.797428,46.793974,-0.778406,-0.297195,7.878161,2.215095,-1.021329,1.646668,2.939821,-1.202392,9.411218,8.632671,96.442079,1271.000000,-0.006800,-671.622956,0.000000,0.000000,148.000000,1935.000000,1451.000000,1081.000000,0.000000
50%,2.817275,20.013331,-0.007336,-0.009562,0.001365,0.000347,2.467988,0.509366,99.918218,3.083939,3.481996,0.678295,0.014545,100.581635,8.027620,79.973740,4.989075,5.151254,68.791299,0.186176,4.854312,-0.007550,997.718354,15.018232,0.890432,0.002582,0.263973,53.133105,1.196375,69.966524,31.015743,35.381980,15.075852,99984.702510,0.528039,0.500114,0.909560,0.409918,0.030502,50.002311,60.049303,10.381110,2106.747397,1.335443,4.884394,70.056176,0.020853,2.786861,0.483200,32.313071,300.629990,10.015601,3.575454,-0.004496,50.004489,0.002439,14.402071,13.907039,0.030941,0.682508,-0.000234,50.008291,5.577156,-0.010455,1.033660,-0.952967,50.027027,1.000000,10.048249,0.006685,-6.441992,3.461849,2.138771,100.172805,50.043094,0.004214,0.439960,9.927533,3.003166,-0.011712,4.110472,3.901630,0.049476,10.405881,9.967244,99.895267,1471.000000,0.000100,10.071374,0.000000,0.000000,278.000000,2028.000000,2686.000000,1265.000000,0.000000
75%,4.223699,21.083448,1.041062,0.882272,0.925603,0.980095,3.797335,1.200406,108.722557,6.243081,5.322923,1.260943,1.004756,101.403862,9.551301,86.043355,7.413721,14.573628,88.081697,0.902518,6.604764,1.058635,1069.712621,17.467351,1.879663,1.171711,1.100175,57.000415,2.167218,72.890605,33.266606,52.287895,18.070746,100920.654749,1.457480,1.209518,1.946131,1.362012,1.238546,52.911483,63.713410,12.256011,2735.707636,2.425340,9.740571,73.374176,0.909224,4.202790,1.466941,38.977898,300.629990,13.022810,5.148163,0.957937,53.416694,1.002648,14.402071,18.424117,0.933835,0.959959,-0.000234,54.201324,9.487395,1.000467,2.149136,-0.185170,52.929501,1.000000,11.966315,1.019745,-4.717504,5.244378,2.138771,107.220602,53.237523,0.814972,1.174502,12.783388,3.791607,1.005278,6.106678,4.896051,1.274605,11.518549,11.336859,103.480639,1698.000000,0.006700,689.172557,1.000000,0.000000,2611.000000,2050.000000,2703.000000,4643.000000,0.000000
max,11.737364,25.808760,4.653302,4.709272,5.096100,5.326779,17.165790,4.666843,148.312826,11.102173,22.916481,4.793638,5.780608,104.753426,16.332891,92.750969,19.075814,168.295257,212.245584,3.961364,16.545180,6.185420,1356.405814,29.780369,7.167330,4.446820,19.742288,76.805418,17.615444,87.684249,44.021192,154.051594,19.999856,104781.467076,4.903801,4.225407,11.897106,5.729408,7.053765,69.570256,82.679059,17.822711,5358.085268,9.500742,33.050567,88.493905,5.468435,12.775425,6.542576,51.602898,497.744141,18.513492,16.569833,7.490917,68.030550,5.049130,29.656030,50.490992,4.690205,2.558823,4.469949,75.415573,46.043522,5.298340,80.679684,3.162323,64.953591,1.000000,17.597005,5.637256,3.149156,19.633040,16.005969,142.512136,69.874858,4.254048,4.904895,34.263562,7.286726,5.410440,15.462965,9.712523,6.536391,16.192126,17.939226,120.527536,1748.000000,0.048300,3869.733323,1.000000,1.000000,2611.000000,2055.000000,2703.000000,4643.000000,1.000000

In [31]:
# lets find the percentage of null values in each of the column from the clearner version of data
total =tst_clean .isnull().sum().sort_values(ascending=False)
miss_perc = tst_clean.isnull().sum()/tst_clean.isnull().count()*100
percent= (round(miss_perc, 1)).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', '%'])
missing_data

      Total     %
x44    8566  85.7
x30    8085  80.8
x57    8077  80.8
x55    4424  44.2
x52    4080  40.8
x49    3254  32.5
x54    3206  32.1
x95    3172  31.7
x74    3163  31.6
x78    2866  28.7
x16    2753  27.5
x89    2675  26.8
x14    2428  24.3
x85    2419  24.2
x42    2418  24.2
x41    2404  24.0
x45    2063  20.6
x61    1766  17.7
x96    1628  16.3
x76    1356  13.6
x11    1329  13.3
x80    1315  13.2
x91    1310  13.1
x75    1266  12.7
x64    1262  12.6
x92     626   6.3
x67     620   6.2
x26     617   6.2
x94     615   6.2
x22     613   6.1
x79     610   6.1
x5      602   6.0
x86     602   6.0
x68     600   6.0
x88     591   5.9
x63     587   5.9
x83     572   5.7
x38     565   5.6
x21       0   0.0
x6        0   0.0
x40       0   0.0
x2        0   0.0
x37       0   0.0
x36       0   0.0
x4        0   0.0
x35       0   0.0
x34       0   0.0
x12       0   0.0
x32       0   0.0
x8        0   0.0
x23       0   0.0
x29       0   0.0
x9        0   0.0
x28       0   0.0
x17       0   0.0
x27       0   0.0
x15       0   0.0
x13       0   0.0
x10       0   0.0
x20       0   0.0
x25       0   0.0
x18       0   0.0
x93       0   0.0
x43       0   0.0
x81       0   0.0
x65       0   0.0
x60       0   0.0
x33       0   0.0
x31       0   0.0
x24       0   0.0
x19       0   0.0
x7        0   0.0
x3        0   0.0
x100      0   0.0
x97       0   0.0
x90       0   0.0
x87       0   0.0
x84       0   0.0
x82       0   0.0
x73       0   0.0
x46       0   0.0
x72       0   0.0
x71       0   0.0
x70       0   0.0
x69       0   0.0
x66       0   0.0
x62       0   0.0
x58       0   0.0
x56       0   0.0
x77       0   0.0
x53       0   0.0
x51       0   0.0
x50       0   0.0
x48       0   0.0
x47       0   0.0
x1        0   0.0

Without bclearly kowing the physical meaning of all these columns and trying to impute allthese columns with nemerical values is not making sense. So, an choosing an arbitarary percentage cut off of 20% and will drop the columns that has missing values of more than 20%.

In [32]:
#dropping columns with missing values more than 20%
tst_df = tst_clean.loc[:, tst_clean.isnull().mean() < .20]

In [33]:
tst_df.shape

(10000, 79)

In [34]:
#Now lets do the numerical imputation for all numerical values using iterative imputer. Doing multiple imputation 
#does not make sense here since we dont know what these varaible and features really mean>

from fancyimpute import IterativeImputer

#calling MICE imputer
mice_imp = IterativeImputer()
#now impute missing values with MICEimputer
imp_tst_df = pd.DataFrame(mice_imp.fit_transform(tst_df))
imp_tst_df.index = tst_df.index
imp_tst_df.columns = tst_df.columns

In [35]:
NAs = pd.concat([imp_tst_df.isnull().sum()], axis=1)
NAs[NAs.sum(axis=1) > 0]

Empty DataFrame
Columns: [0]
Index: []

In [36]:
imp_tst_df.shape

(10000, 79)

In [37]:
# now lets rearrange the columns for the cleaner data

imp_tst_df=imp_tst_df[['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9','x10',
                       'x11', 'x12', 'x13', 'x15', 'x17', 'x18', 'x19','x20',
                       'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29',
                       'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38','x40',
                       'x43', 'x46', 'x47', 'x48', 'x50','x51', 'x53', 'x56', 'x58', 'x60',
                       'x61', 'x62', 'x63', 'x64', 'x65', 'x66', 'x67', 'x68', 'x69','x70',
                       'x71', 'x72', 'x73','x75', 'x76', 'x77', 'x79','x80',
                       'x81', 'x82', 'x83', 'x84', 'x86', 'x87', 'x88','x90',
                       'x91', 'x92', 'x93', 'x94', 'x96', 'x97', 'x100']]

In [38]:
imp_tst_df.head()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x15,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x31,x32,x33,x34,x35,x36,x37,x38,x40,x43,x46,x47,x48,x50,x51,x53,x56,x58,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x75,x76,x77,x79,x80,x81,x82,x83,x84,x86,x87,x88,x90,x91,x92,x93,x94,x96,x97,x100
0,4.747627,20.509439,1748.0,2.299105,-1.815777,-0.752166,0.0098,-3.240309,0.587948,-0.260721,101.113628,-0.812035,3.251085,-0.917763,7.097387,75.256714,120.216190,8.269754,4.794438,56.134458,-0.083641,0.0,5.740955,-3.152540,924.013304,17.697125,1.402273,0.0,1.461654,475.0,57.930285,4.727300,66.416594,28.450466,33.499310,16.776061,-0.963616,1.266416,53.020326,61.840284,1825.413159,2.517924,70.880778,0.239009,300.62999,211.0,5.461123,5.149473,1.179229,59.346822,2703.0,2.219502,17.667792,5.557066,-2.030901,0.636111,-0.000234,62.363381,4.613878,3.632041,-0.382482,1081.0,1.0,8.325299,-1.274085,-5.663245,2.402660,-0.061040,64.002500,0.548974,3.420875,5.904644,0.693343,12.542333,0.0,3.107683,12.438759,7.298306,93.567120
1,1.148654,19.301465,1471.0,1.862200,-0.773707,-1.461276,0.0076,0.443209,0.522113,-1.090886,104.791999,8.805876,1.651993,-1.396065,7.117930,79.061540,-267.562586,5.668347,12.377178,72.126007,0.321981,0.0,2.058123,-0.442525,1107.628399,15.747234,2.027073,1.0,0.608259,238.0,55.646392,0.789132,68.881807,32.242558,-1.034680,11.959804,1.001799,5.873890,49.116516,61.279131,1818.390072,2.269700,69.832156,-1.214940,300.62999,2050.0,6.520113,2.101449,-0.871509,59.500142,2686.0,1.289800,14.402071,7.302161,-1.553879,1.352019,-0.000234,54.104054,9.010198,1.489493,-1.106853,4643.0,1.0,6.088895,1.878944,-8.237793,3.636347,3.726452,53.387201,-0.751229,0.295234,4.876645,-0.848567,7.213829,1.0,4.276078,10.386987,12.527094,98.607486
2,4.986860,18.769675,1271.0,1.040845,-1.548690,2.632948,-0.0005,-1.167885,5.739275,0.222975,102.109546,7.831517,3.055358,1.057296,10.943217,87.567827,-311.292903,3.219583,31.135956,50.048638,1.174485,1.0,1.609278,-0.303259,1009.911508,12.008190,0.618778,0.0,0.680923,2611.0,53.178113,0.869321,70.249633,35.207243,48.980294,14.564732,-0.490053,0.750075,48.258898,63.737244,1815.680559,1.704048,67.090400,1.428580,300.62999,1935.0,12.190433,1.793349,-0.114922,48.121885,2703.0,-1.755707,14.402071,9.903803,1.720469,0.765756,-0.000234,51.522621,11.700359,0.383319,-1.078648,4643.0,1.0,8.711055,-0.073306,-8.739095,4.424095,2.138771,49.687134,2.641871,1.718243,4.455432,1.143388,10.483928,0.0,2.090868,11.328177,11.628247,94.578246
3,3.709183,18.374375,1698.0,-0.169882,-2.396549,-0.784673,-0.0160,-2.662226,1.548050,0.210141,82.653354,0.436885,1.578106,-1.287913,6.588790,71.825782,2229.149400,7.459929,1.822459,88.144007,0.909556,0.0,8.864059,0.641209,841.889126,20.904196,0.725017,0.0,0.622849,85.0,50.311869,0.453211,65.253390,34.432292,52.756665,18.503815,-0.007376,-0.455920,44.525657,60.008453,2251.680231,2.915405,75.219207,-0.415800,300.62999,2050.0,6.865209,5.083537,1.685063,46.761738,1332.0,-0.807993,14.402071,16.576216,0.033036,0.284538,-0.000234,54.625974,13.160347,2.171326,-0.109125,1209.0,1.0,11.742605,-0.253294,-6.641284,4.755348,2.138771,50.702155,1.811825,0.461637,3.947223,0.693646,3.862867,0.0,2.643847,10.064961,10.550014,100.346261
4,3.801616,20.205541,1527.0,2.092652,-0.732784,-0.703101,0.0186,0.056422,2.878167,-0.457618,75.036421,8.034303,1.631426,0.349166,5.777599,74.602441,-469.049530,8.245194,0.904920,51.705319,-0.544762,0.0,2.408958,1.841905,885.172420,14.401750,4.059599,1.0,1.073262,236.0,39.646787,-0.686812,71.673393,37.257458,64.572325,11.477353,0.432984,2.684343,46.377723,55.276157,3377.213091,0.461064,64.547880,3.294733,300.62999,1935.0,8.733307,4.758357,-1.053362,49.328246,2703.0,-0.943724,15.155869,24.834647,3.127852,1.427115,-0.000234,55.277258,14.443014,6.086487,-1.002809,4643.0,0.0,11.602066,0.091523,-4.620275,2.060447,2.138771,49.747279,0.320393,0.930729,1.637334,-0.834763,3.632039,1.0,4.074434,9.255766,12.716137,102.578918

In [39]:
imp_tst_df.shape

(10000, 79)

In [40]:
NAs = pd.concat([imp_tst_df.isnull().sum()], axis=1)
NAs[NAs.sum(axis=1) > 0]

Empty DataFrame
Columns: [0]
Index: []

In [41]:
#Importing scikit-learn modules from library
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA

In [42]:
# lets check with simple person correlation and see if any columns are highly correlated

def correlation(df, threshold):
    col_corr=set()
    corr_matrix=df.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j])>threshold:
                colname=corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features=correlation(imp_tst_df, 0.6)
#len(set(corr_features))
corr_features

{'x36', 'x47', 'x61', 'x70'}

the result is based on simple corelation.

In [77]:
# I will do one more test for multi colinearlity and see what stands out.
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif =pd.DataFrame()
vif['Variance inflation factor'] = [variance_inflation_factor(imp_tst_df.values, i) for i in range(imp_tst_df.shape[1])]
vif['feature names'] = imp_tst_df.columns
#Its normally that we use 10 as threshold to cut off varaiance of the data. But in this data since we dont 
#know what most of these feature really means and I have already filles null values with interative and frequency 
#so I am going to use a higher value of 100

high_vif_col = vif[vif['Variance inflation factor']>=10]
high_vif_col = vif[vif['Variance inflation factor']<2]

In [78]:
high_vif_col

    Variance inflation factor feature names
3                    1.900605            x4
6                    1.007661            x7
16                   1.008405           x19
20                   1.812207           x23
21                   1.830256           x24
27                   1.658675           x31
29                   1.684651           x33
36                   1.649672           x43
56                   1.046828           x71
70                   1.381237           x88
74                   1.596847           x93

In [89]:
# Now lest drop these columns from the imputed Training dataframe
test_clean_df=imp_tst_df.drop(['x2','x3','x9','x11','x12','x13','x17','x20','x27','x28','x34','x36','x37',
                                'x47','x48','x53','x56','x58','x64','x65','x67','x68','x69','x72','x73',
                                'x76','x79','x80','x82','x83','x86','x90','x94','x96','x97','x100'], axis=1)

In [90]:
test_clean_df.head()

,x1,x4,x5,x6,x7,x8,x10,x15,x18,x19,x21,x22,x23,x24,x25,x26,x29,x31,x32,x33,x35,x38,x40,x43,x46,x50,x51,x60,x61,x62,x63,x66,x70,x71,x75,x77,x81,x84,x87,x88,x91,x92,x93
0,4.747627,2.299105,-1.815777,-0.752166,0.0098,-3.240309,-0.260721,-0.917763,75.256714,120.216190,4.794438,56.134458,-0.083641,0.0,5.740955,-3.152540,1.402273,0.0,1.461654,475.0,4.727300,33.499310,16.776061,-0.963616,1.266416,1825.413159,2.517924,211.0,5.461123,5.149473,1.179229,2.219502,0.636111,-0.000234,3.632041,1081.0,-1.274085,-0.061040,0.548974,3.420875,0.693343,12.542333,0.0
1,1.148654,1.862200,-0.773707,-1.461276,0.0076,0.443209,-1.090886,-1.396065,79.061540,-267.562586,12.377178,72.126007,0.321981,0.0,2.058123,-0.442525,2.027073,1.0,0.608259,238.0,0.789132,-1.034680,11.959804,1.001799,5.873890,1818.390072,2.269700,2050.0,6.520113,2.101449,-0.871509,1.289800,1.352019,-0.000234,1.489493,4643.0,1.878944,3.726452,-0.751229,0.295234,-0.848567,7.213829,1.0
2,4.986860,1.040845,-1.548690,2.632948,-0.0005,-1.167885,0.222975,1.057296,87.567827,-311.292903,31.135956,50.048638,1.174485,1.0,1.609278,-0.303259,0.618778,0.0,0.680923,2611.0,0.869321,48.980294,14.564732,-0.490053,0.750075,1815.680559,1.704048,1935.0,12.190433,1.793349,-0.114922,-1.755707,0.765756,-0.000234,0.383319,4643.0,-0.073306,2.138771,2.641871,1.718243,1.143388,10.483928,0.0
3,3.709183,-0.169882,-2.396549,-0.784673,-0.0160,-2.662226,0.210141,-1.287913,71.825782,2229.149400,1.822459,88.144007,0.909556,0.0,8.864059,0.641209,0.725017,0.0,0.622849,85.0,0.453211,52.756665,18.503815,-0.007376,-0.455920,2251.680231,2.915405,2050.0,6.865209,5.083537,1.685063,-0.807993,0.284538,-0.000234,2.171326,1209.0,-0.253294,2.138771,1.811825,0.461637,0.693646,3.862867,0.0
4,3.801616,2.092652,-0.732784,-0.703101,0.0186,0.056422,-0.457618,0.349166,74.602441,-469.049530,0.904920,51.705319,-0.544762,0.0,2.408958,1.841905,4.059599,1.0,1.073262,236.0,-0.686812,64.572325,11.477353,0.432984,2.684343,3377.213091,0.461064,1935.0,8.733307,4.758357,-1.053362,-0.943724,1.427115,-0.000234,6.086487,4643.0,0.091523,2.138771,0.320393,0.930729,-0.834763,3.632039,1.0

In [91]:
test_clean_df.shape

(10000, 43)

**Our logistic regression model used only 10 features after reduction. So here I am going to create a new Test data set with only those 10 features after we applied feature reduction.**

In [102]:
test_deploy=test_clean_df[['x7', 'x62', 'x61', 'x40', 'x18', 'x93', 'x66', 'x31', 'x75', 'x50']]

In [103]:
test_deploy.shape

(10000, 10)

# Lets bring the Pickle file for logistic regression, find the probbility of class 1 and retuns a csv file

In [114]:
from sklearn.metrics import roc_auc_score
import pickle
with open('log_model_sm_pickle', 'rb') as f:
    LogReg_model=pickle.load(f)

In [119]:
logReg_probs=LogReg_model.predict_proba()
logReg_result=logReg_probs[:,1].round(decimals=4)

In [120]:
df_LR=pd.DataFrame(logReg_result)
df_LR.to_csv('glmresults.csv', index=False, header=False )

In [121]:
df_LR.describe()

                  0
count  10000.000000
mean       0.976659
std        0.150508
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000

# Lets bring the Pickle file for Random Forest Classifier, find the probbility of class 1 and retuns a csv file

In [147]:
import pickle
with open('rf_pickle', 'rb') as f:
    RandomForest_model=pickle.load(f)

In [148]:
RF_probs=RandomForest_model.predict_proba(test_deploy)
RF_result=RF_probs[:,1].round(decimals=4)

In [149]:
df_rf=pd.DataFrame(RF_result)
df_rf.to_csv('nonglmresults.csv', index=False, header=False)

In [150]:
df_rf.describe()

                  0
count  10000.000000
mean       0.361668
std        0.060660
min        0.140000
25%        0.320000
50%        0.350000
75%        0.400000
max        0.590000

# DONE!!!...